name: Release Datakeeper

on:
  push:
    tags:
    - "v*.*.*" # Trigger on version tags like v1.0.0

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH  # Ensure Poetry is in PATH

    - name: Configure Poetry
      run: |
        poetry config virtualenvs.in-project true  # Keep venv inside project

    - name: Install dependencies with Poetry
      run: |
        poetry install --no-root  # Install only runtime dependencies
        poetry env info
        poetry run pip list

    - name: Build binary with Nuitka
      run: |
        eval $(poetry env activate)
        poetry run nuitka --onefile --standalone --python-flag=no_site \
          --include-package=click \
          --include-package=pyyaml \
          --include-package=apscheduler \
          --output-filename=datakeeper --output-dir=nuitka-build \
          --include-data-file=datakeeper/database/init.sql=datakeeper/database/init.sql \
          --include-data-dir=datakeeper/policy_system/plugins=datakeeper/policy_system/plugins \
          --include-data-file=VERSION=VERSION \
          main.py

    - name: Upload binary to GitHub Releases
      uses: softprops/action-gh-release@v2
      with:
        files: nuitka-build/datakeeper
        body: "🚀 New Nuitka-compiled release of Datakeeper!"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
